name: Tweet every hour

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Tweepy
        run: pip install tweepy

      - name: Run bot
        run: python main.py

